// Массив товаров каталога. Схема объекта:
// { id, name, parentCategory (slug), subcategory (categoryKey), material, brand, article, price, priceUnit (опц., единица цены — по умолчанию 'шт.'), inStock, image }

export const PRODUCTS = [
  {
    id: '1',
    name: 'Болт 16х90 мм DIN 933 полная резьба, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Медь',
    brand: 'TCS',
    article: '045-1290',
    price: 7.87,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/1.jpg',
  },
  {
    id: '2',
    name: 'Винт с внутренним шестигранником 8х40 мм класс прочности 8.8 DIN 912 полная резьба, оцинкованный',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Медь',
    brand: 'CONTAINERD',
    article: '112-3380',
    price: 15.24,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/2.jpg',
  },
  {
    id: '3',
    name: 'Винт установочный с внутр. шестигранником 8х40 мм, класс прочности 12.9 DIN 913 тупой конец, черный',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Алюминий',
    brand: 'SUPERMICRO',
    article: '078-2240',
    price: 55.52,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/3.jpg',
  },
  {
    id: '4',
    name: 'Болт 12х150 мм DIN 933 полная резьба, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Алюминий',
    brand: 'SUPERMICRO',
    article: '203-1150',
    price: 77.12,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/4.jpg',
  },
  {
    id: '5',
    name: 'Гайка с фланцем М10 DIN 6923 оцинкованная',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Латунь',
    brand: 'ZABKA',
    article: '016-9070',
    price: 8.93,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/5.jpg',
  },
  {
    id: '6',
    name: 'Гайка крыльчатая врезная М10 DIN 1624 оцинкованная',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Цинк',
    brand: 'COMSOL',
    article: '134-5520',
    price: 13.54,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/6.jpg',
  },
  {
    id: '7',
    name: 'Анкер химический BIT-STICK 300 мл (полиэстер)',
    category: 'chemical-anchor',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'chemical-anchor',
    material: 'Полиэстер',
    brand: 'COMSOL',
    article: '091-6610',
    price: 2540.87,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/7.jpg',
  },
  {
    id: '8',
    name: 'Анкер химический VMU plus картридж 410 мл + 2 смесителя, винилэстеровая смола',
    category: 'chemical-anchor',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'chemical-anchor',
    material: 'Винилэстеровая смола',
    brand: 'COMSOL',
    article: '167-4830',
    price: 1560.87,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/8.jpg',
  },

  // --- Болты ---
  {
    id: '9',
    name: 'Болт М8×40 DIN 931 частичная резьба, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Оцинкованная сталь',
    brand: 'TCS',
    article: '021-8440',
    price: 5.20,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '10',
    name: 'Болт М10×60 DIN 933 полная резьба, нержавеющая сталь А2',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Нержавеющая сталь',
    brand: 'CONTAINERD',
    article: '033-1060',
    price: 18.90,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '11',
    name: 'Болт М12×80 DIN 933 полная резьба, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Оцинкованная сталь',
    brand: 'TCS',
    article: '044-1280',
    price: 24.50,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '12',
    name: 'Болт М6×30 DIN 933 полная резьба, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Оцинкованная сталь',
    brand: 'ZABKA',
    article: '018-0630',
    price: 3.40,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '13',
    name: 'Болт М16×100 DIN 931 частичная резьба, класс прочности 10.9',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Углеродистая сталь',
    brand: 'SUPERMICRO',
    article: '057-1610',
    price: 62.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '14',
    name: 'Болт М20×120 DIN 931 частичная резьба, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Оцинкованная сталь',
    brand: 'TCS',
    article: '069-2012',
    price: 98.30,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '15',
    name: 'Болт М8×70 DIN 933 полная резьба, нержавеющая сталь А4',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Нержавеющая сталь',
    brand: 'CONTAINERD',
    article: '041-0870',
    price: 27.60,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '16',
    name: 'Болт М10×30 DIN 933 полная резьба, латунь',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Латунь',
    brand: 'NETGEAR',
    article: '027-1030',
    price: 34.10,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '17',
    name: 'Болт фундаментный М12×200 ГОСТ 24379.1, оцинкованный',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Оцинкованная сталь',
    brand: 'ZABKA',
    article: '083-1220',
    price: 115.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '18',
    name: 'Болт М14×90 DIN 931 частичная резьба, класс прочности 8.8',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Углеродистая сталь',
    brand: 'SUPERMICRO',
    article: '062-1490',
    price: 47.80,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '19',
    name: 'Болт М8×50 DIN 933 полная резьба, углеродистая сталь',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Углеродистая сталь',
    brand: 'TCS',
    article: '036-0850',
    price: 9.90,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '20',
    name: 'Болт М24×150 DIN 931 частичная резьба, класс прочности 10.9',
    category: 'bolt',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'bolt',
    material: 'Углеродистая сталь',
    brand: 'NETGEAR',
    article: '096-2415',
    price: 234.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },

  // --- Винты ---
  {
    id: '21',
    name: 'Саморез по дереву 4.2×75 мм с потайной головкой PZ2, жёлтая пассивация',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Оцинкованная сталь',
    brand: 'ZABKA',
    article: '011-4275',
    price: 2.10,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '22',
    name: 'Шуруп универсальный 3.5×35 мм PZ2, оцинкованный',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Оцинкованная сталь',
    brand: 'TCS',
    article: '014-3535',
    price: 1.60,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '23',
    name: 'Винт с цилиндрической головкой М6×20 DIN 84 шлиц прямой, оцинкованный',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Оцинкованная сталь',
    brand: 'CONTAINERD',
    article: '019-0620',
    price: 4.50,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '24',
    name: 'Саморез кровельный 4.8×35 мм с шестигранной головкой, RAL 9003 белый',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Оцинкованная сталь',
    brand: 'SUPERMICRO',
    article: '025-4835',
    price: 3.80,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '25',
    name: 'Винт М5×16 DIN 7985 с полукруглой головкой PH2, нержавеющая сталь А2',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Нержавеющая сталь',
    brand: 'NETGEAR',
    article: '022-0516',
    price: 8.20,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '26',
    name: 'Шуруп ГКЛ 3.5×55 мм PZ2, фосфатированный',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Углеродистая сталь',
    brand: 'ZABKA',
    article: '017-3555',
    price: 1.90,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '27',
    name: 'Винт самонарезающий 4.2×13 мм для тонкого металла, оцинкованный',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Оцинкованная сталь',
    brand: 'TCS',
    article: '013-4213',
    price: 1.20,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '28',
    name: 'Саморез с прессшайбой 4.2×19 мм острый, нержавеющая сталь А2',
    category: 'screw',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'screw',
    material: 'Нержавеющая сталь',
    brand: 'CONTAINERD',
    article: '020-4219',
    price: 6.70,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },

  // --- Гайки ---
  {
    id: '29',
    name: 'Гайка шестигранная М10 DIN 934 класс прочности 8, оцинкованная',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Оцинкованная сталь',
    brand: 'SUPERMICRO',
    article: '031-1010',
    price: 5.60,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '30',
    name: 'Гайка самостопорящаяся М12 DIN 985, нержавеющая сталь А2',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Нержавеющая сталь',
    brand: 'NETGEAR',
    article: '038-1212',
    price: 16.40,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '31',
    name: 'Гайка шестигранная М16 DIN 934 класс прочности 8.8, оцинкованная',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Оцинкованная сталь',
    brand: 'TCS',
    article: '045-1616',
    price: 21.00,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '32',
    name: 'Гайка колпачковая М8 DIN 1587, нержавеющая сталь А2',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Нержавеющая сталь',
    brand: 'COMSOL',
    article: '029-0808',
    price: 12.30,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '33',
    name: 'Гайка удлинённая М10 DIN 6334, оцинкованная',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Оцинкованная сталь',
    brand: 'ZABKA',
    article: '037-1010',
    price: 23.80,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '34',
    name: 'Гайка шестигранная М6 DIN 934, нержавеющая сталь А4',
    category: 'nut',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'nut',
    material: 'Нержавеющая сталь',
    brand: 'CONTAINERD',
    article: '024-0606',
    price: 9.10,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },

  // --- Анкеры ---
  {
    id: '35',
    name: 'Анкер-клин LB 10×52 М8, оцинкованный',
    category: 'anchor',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'anchor',
    material: 'Оцинкованная сталь',
    brand: 'SUPERMICRO',
    article: '053-1052',
    price: 38.40,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '36',
    name: 'Анкер забивной M10×30 D15, оцинкованный',
    category: 'anchor',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'anchor',
    material: 'Оцинкованная сталь',
    brand: 'NETGEAR',
    article: '047-1030',
    price: 29.60,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '37',
    name: 'Анкер распорный M12×60 с конической гайкой, нержавеющая сталь А4',
    category: 'anchor',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'anchor',
    material: 'Нержавеющая сталь',
    brand: 'TCS',
    article: '061-1260',
    price: 87.50,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '38',
    name: 'Анкер рамный нейлоновый 10×135 мм с шурупом',
    category: 'anchor',
    parentCategory: 'stroitelnyj-krepyozh',
    subcategory: 'anchor',
    material: 'Нейлон',
    brand: 'COMSOL',
    article: '073-1013',
    price: 18.90,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },

  // --- Химические анкеры ---
  {
    id: '39',
    name: 'Анкер химический HY-100 картридж 150 мл, гибридный полиуретан',
    category: 'chemical-anchor',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'chemical-anchor',
    material: 'Гибридный полиуретан',
    brand: 'TCS',
    article: '102-1500',
    price: 890.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '40',
    name: 'Анкер химический HPM-500 картридж 280 мл, эпоксидная смола + 2 смесителя',
    category: 'chemical-anchor',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'chemical-anchor',
    material: 'Эпоксидная смола',
    brand: 'SUPERMICRO',
    article: '118-2800',
    price: 3150.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '41',
    name: 'Картридж инъекционный RI-07 PLUS 300 мл, полиэстер + 2 смесителя',
    category: 'chemical-anchor',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'chemical-anchor',
    material: 'Полиэстер',
    brand: 'COMSOL',
    article: '109-3000',
    price: 1240.00,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '42',
    name: 'Анкер химический VEA-500 400 мл, акрилат + смеситель',
    category: 'chemical-anchor',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'chemical-anchor',
    material: 'Акрилат',
    brand: 'ZABKA',
    article: '125-4000',
    price: 1890.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },

  // --- Герметик и силикон ---
  {
    id: '43',
    name: 'Герметик силиконовый нейтральный 310 мл, прозрачный, −60…+180 °C',
    category: 'sealant',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'sealant',
    material: 'Силикон',
    brand: 'NETGEAR',
    article: '201-3100',
    price: 320.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '44',
    name: 'Силикон санитарный 280 мл белый, влагостойкий с фунгицидом',
    category: 'sealant',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'sealant',
    material: 'Силикон',
    brand: 'TCS',
    article: '208-2800',
    price: 285.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '45',
    name: 'Герметик акриловый 280 мл белый, окрашиваемый, морозостойкий',
    category: 'sealant',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'sealant',
    material: 'Акрил',
    brand: 'CONTAINERD',
    article: '215-2800',
    price: 190.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },

  // --- Монтажная пена ---
  {
    id: '46',
    name: 'Монтажная пена профессиональная 750 мл, зимняя −10 °C, B2',
    category: 'foam',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'foam',
    material: 'Полиуретан',
    brand: 'COMSOL',
    article: '301-7500',
    price: 540.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
  {
    id: '47',
    name: 'Монтажная пена бытовая 500 мл летняя, выход 45 л',
    category: 'foam',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'foam',
    material: 'Полиуретан',
    brand: 'ZABKA',
    article: '310-5000',
    price: 310.00,
    priceUnit: 'шт.',
    inStock: false,
    image: '/product_card/placeholder.jpg',
  },

  // --- Жидкие гвозди ---
  {
    id: '48',
    name: 'Жидкие гвозди суперсильные Fix-All 290 мл, белые, нагрузка до 150 кг',
    category: 'liquid-nails',
    parentCategory: 'himicheskij-krepyozh',
    subcategory: 'liquid-nails',
    material: 'Полиуретан',
    brand: 'NETGEAR',
    article: '401-2900',
    price: 480.00,
    priceUnit: 'шт.',
    inStock: true,
    image: '/product_card/placeholder.jpg',
  },
]
